- hosts: testing 
  sudo: true
  remote_user: sysadmin

  vars:
    # for newer ubuntus.. (pending testing)
    ansible_python_interpreter: /usr/bin/python2.7
    no_python2: true	
    # Ossec server rules
    ossec_server_ip: '10.2.5.2'
    ossec_server_fqdn: 'i_dont_know_yet'
    ossec_server_name: 'i_dont_know_yet'
    ossec_managed_server: true
    # Normal OS Hardening suggested by community
    os_security_users_allow: change_user
    os_security_kernel_enable_core_dump: false
    os_security_suid_sgid_remove_from_unknown: true
    os_auth_pam_passwdqc_enable: false
    os_desktop_enable: true
    os_env_extra_user_paths: ['/home']
    os_auth_allow_homeless: true
    os_security_suid_sgid_blacklist: ['/bin/umount']
    os_security_suid_sgid_whitelist: ['/usr/bin/rlogin']
    # Malware scanner cronjobs
    lynis_cron: /usr/local/lynis/lynis -c --cronjob --upload --profile /usr/local/lynis/custom.prf
    maldet_cron: /usr/local/maldetect/maldet -b -r / 1 >> /dev/null 2>&1
    lynis_version: lynis-2.4.4.tar.gz

  roles:
    - common
    - ansible-apparmor # AppArmor configuration
#    - ansible-ossec-agent  # OSSEC implementation for Monitoring team
    - ansible-os-hardening # Basic Kernel / OS hardening stuff
