---
- name: upgrade packages
  apt:
    update_cache: yes
    upgrade: full

- name: install common packages
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
  with_items:
    - mc
    - ufw
