---
- name: enable firewall
  ufw:
    state: enabled
    policy: allow

- name: allow ssh
  ufw:
    direction: in
    rule: allow
    proto: tcp
    port: 22

- name: allow http
  ufw:
    direction: in
    rule: allow
    proto: tcp
    port: 80

- name: allow http443
  ufw:
    direction: in
    rule: allow
    proto: tcp
    port: 443

- name: deny incoming
  ufw:
    policy: deny
    direction: incoming
