---
- name: uninstall unneeded services
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - rpcbind
    - snmpd
    - libsnmp-base
    - ntpd
    - ntp
    - openntpd
    - exim4
    - exim4-base
    - exim4-daemon-light 
    - usbmuxd
    - ircd
    - knockd