---
- name: upgrade packages
  apt:
    update_cache: yes
    upgrade: full

- name: install common packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - curl
    - htop
    - ufw
    - rkhunter
    - chkrootkit 
