---
- name: move broken hook
  raw: sudo mv /usr/share/initramfs-tools/hooks/resume /home/sysadmin
  ignore_errors: true
- name: apt-get update
  raw: apt-get update -qq
  when: no_python2
- name: Install python 2.7
  raw: apt-get install -qq python2.7
  when: no_python2
- name: Install sudo
  raw: apt-get install -qq sudo
- name: install aptitude
  apt:
    name: aptitude
    state: latest
