---
- name: reinstall ssh packages
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - openssh-client
    - openssh-server

- name: reinstall linux kernel
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - linux-image-generic
    - linux-image
